services:
  batavianovadigitalbank.identity:
    image: ${DOCKER_REGISTRY-}batavianovadigitalbankidentity
    build:
      context: .
      dockerfile: BataviaNovaDigitalBank/Dockerfile

  batavianovadigitalbank.web:
    image: ${DOCKER_REGISTRY-}batavianovadigitalbankweb
    build:
      context: .
      dockerfile: BataviaNovaDigitalBank.Web/Dockerfile

